import { expect, test, type Page } from "@playwright/test";
import { gotoApp, readSource, resetStorageBeforeNavigation, setSource, waitForHitRegions } from "./helpers";

/**
 * Verbatim output of `circuit.build_circuit` for one nMOS + one resistor, after §S2.2 taught the
 * generator to emit named pins. Kept as a fixture so the assertion does not depend on the MCP
 * process running: what matters is that the editor can address these pins.
 */
const MCP_GENERATED = String.raw`\begin{tikzpicture}
  % --- circuit generated by circuit-mcp ---
  % component M1 (nmos) at (0, 0)
  \begin{scope}[xshift={-17pt}, yshift={4pt}]
    \draw[line width=0.32mm, line cap=round] (0.3,0.5) -- (0.56,0.5);
    \draw[line width=0.7mm] (0.55,0.25) -- (0.55,0.75);
    \draw[line width=0.7mm] (0.7,0.2) -- (0.7,0.8);
    \draw[line width=0.32mm, line cap=round, line join=round] (0.7,0.70) -- (1.03,0.70) --(1.03,1);
    \draw[-{Triangle[length=2mm, width=1.5mm, sep=-1.2pt]}, line width=0.32mm, line cap=round] (0.7,0.3) -- (1.0,0.3);
    \draw[line width=0.32mm, line cap=round] (1.03,0.291) -- (1.03,0);
    \node[node font=\sffamily\bfseries] at (0,0.54) {$M_1$};
    \coordinate (node_M1.g) at (0.3,0.5);
    \coordinate (node_M1.d) at (1.03,1);
    \coordinate (node_M1.s) at (1.03,0);
  \end{scope}
  % component R1 (resistor) at (0.78, 4)
  \begin{scope}[xshift={22.193pt}, yshift={113.811pt}]
    \draw[line width=0.32mm, line cap=round] (-0.35,0) -- (-0.195,0) -- (-0.1625,0.15) -- (-0.0975,-0.15) -- (-0.0325,0.15) -- (0.0325,-0.15) -- (0.0975,0.15) -- (0.1625,-0.15) -- (0.195,0) -- (0.35,0);
    \node at (0.05,0.35) {$R_D$};
    \coordinate (node_R1.l) at (-0.35,0);
    \coordinate (node_R1.r) at (0.35,0);
  \end{scope}
  % wire w1
  \draw[thick, line cap=round] (-0.297,0.641) -- (-0.500,0.640);
  % wire w2
  \draw[thick, line cap=round] (0.433,1.141) -- (0.430,4.000);
  % wire w3
  \draw[thick, line cap=round] (0.433,0.141) -- (0.430,-1.000);
\end{tikzpicture}`;

async function activateTool(page: Page, mode: string): Promise<void> {
  await page.evaluate((nextMode) => {
    const api = (globalThis as unknown as {
      __TIKZ_EDITOR_APP_TEST_API__?: { dispatch?: (action: unknown) => void };
    }).__TIKZ_EDITOR_APP_TEST_API__;
    api?.dispatch?.({ type: "SET_TOOL_MODE", mode: nextMode });
  }, mode);
}

/** Hover sampled points across every hit region until dots for `anchorNode` show up. */
async function revealAnchorNames(page: Page, anchorNode: string): Promise<string[]> {
  const regions = page.locator("[data-hit-region-target-id]");
  const dots = page.locator(`[data-testid="node-anchor-dot"][data-anchor-node="${anchorNode}"]`);
  for (let index = 0; index < (await regions.count()); index += 1) {
    const box = await regions.nth(index).boundingBox();
    if (!box) continue;
    for (const fx of [0.5, 0.9, 0.98, 0.1, 0.02]) {
      for (const fy of [0.5, 0.1, 0.9]) {
        await page.mouse.move(box.x + box.width * fx, box.y + box.height * fy, { steps: 6 });
        await page.waitForTimeout(80);
        const count = await dots.count();
        if (count > 0) {
          return await dots.evaluateAll((nodes) =>
            nodes.map((n) => n.getAttribute("data-anchor-name") ?? "")
          );
        }
      }
    }
  }
  return [];
}

test.beforeEach(async ({ page }) => {
  await resetStorageBeforeNavigation(page);
});

test("circuit-mcp output carries addressable pins the editor can reveal", async ({ page }) => {
  await gotoApp(page);
  await setSource(page, MCP_GENERATED);
  await waitForHitRegions(page, 1);

  // The generator must have written the pins into the source.
  const source = await readSource(page);
  expect(source).toContain("\\coordinate (node_M1.d)");
  expect(source).toContain("\\coordinate (node_R1.l)");

  await activateTool(page, "addOrthoWire");

  const mosPins = await revealAnchorNames(page, "node_M1");
  const resistorPins = await revealAnchorNames(page, "node_R1");
  console.log("[MCP-PINS] node_M1 anchors:", JSON.stringify(mosPins));
  console.log("[MCP-PINS] node_R1 anchors:", JSON.stringify(resistorPins));

  // This is the whole point of §S2.2: before it, every one of these counts was 0 and the
  // generated circuit could not be wired at all.
  expect(mosPins.sort()).toEqual(["d", "g", "s"]);
  expect(resistorPins.sort()).toEqual(["l", "r"]);
});
